# Generated by Django 5.2.17 on 2026-09-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'categoria de despesa',
                'verbose_name_plural': 'categorias de despesas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Identificador como CAIXA ou NUBANK-PASTIFICIO.', max_length=30, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('account_type', models.CharField(choices=[('cash', 'Dinheiro em caixa'), ('bank_account', 'Conta bancária'), ('payment_platform', 'Conta em intermediador de pagamentos'), ('other', 'Outra')], default='bank_account', max_length=30, verbose_name='tipo de conta')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'conta financeira',
                'verbose_name_plural': 'contas financeiras',
                'ordering': ['name'],
            },
        ),
    ]
