# Generated by Django 5.2.17 on 2026-09-27 11:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('purchases', '0004_purchasepayment_financial_account_and_more'),
        ('sales', '0003_salesorderpayment_financial_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('incoming', 'Entrada'), ('outgoing', 'Saída')], max_length=10, verbose_name='direção')),
                ('kind', models.CharField(choices=[('opening_balance', 'Saldo inicial'), ('purchase_payment', 'Pagamento de compra'), ('sale_receipt', 'Recebimento de venda'), ('sale_fee', 'Taxa de recebimento'), ('expense_payment', 'Pagamento de despesa'), ('owner_deposit', 'Depósito do proprietário'), ('owner_reimbursement', 'Reembolso ao proprietário'), ('transfer', 'Transferência entre contas'), ('adjustment', 'Ajuste de saldo'), ('reversal', 'Estorno')], max_length=30, verbose_name='tipo de movimentação')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('occurred_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='data da movimentação')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('source_key', models.CharField(editable=False, max_length=100, unique=True, verbose_name='identificador da operação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.financialaccount', verbose_name='conta financeira')),
                ('purchase_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements', to='purchases.purchasepayment', verbose_name='pagamento de compra')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.financialmovement', verbose_name='movimentação estornada')),
                ('sales_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements', to='sales.salesorderpayment', verbose_name='pagamento de venda')),
            ],
            options={
                'verbose_name': 'movimentação financeira',
                'verbose_name_plural': 'movimentações financeiras',
                'ordering': ['-occurred_on', '-id'],
                'indexes': [models.Index(fields=['financial_account', 'occurred_on'], name='finance_account_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_movement_amount_positive'), models.CheckConstraint(condition=models.Q(('purchase_payment__isnull', True), ('sales_payment__isnull', True), _connector='OR'), name='finance_movement_single_payment_source'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'reversal'), ('reversal_of__isnull', False)), models.Q(models.Q(('kind', 'reversal'), _negated=True), ('reversal_of__isnull', True)), _connector='OR'), name='finance_movement_reversal_link_valid'), models.UniqueConstraint(condition=models.Q(('purchase_payment__isnull', False), ('reversal_of__isnull', True)), fields=('purchase_payment', 'kind'), name='finance_purchase_movement_unique'), models.UniqueConstraint(condition=models.Q(('reversal_of__isnull', True), ('sales_payment__isnull', False)), fields=('sales_payment', 'kind'), name='finance_sales_movement_unique')],
            },
        ),
    ]
