# Generated by Django 5.2.17 on 2026-09-03 18:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_remove_stockcountline_stock_count_counted_nonnegative_and_more'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Identificador como PROD-2026-000001.', max_length=50, unique=True, verbose_name='código do lote de produção')),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('in_progress', 'Em produção'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], db_index=True, default='planned', max_length=20, verbose_name='situação')),
                ('planned_quantity', models.DecimalField(decimal_places=6, help_text='Quantidade planejada na unidade-base do item produzido.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='quantidade planejada')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='quantidade efetivamente produzida')),
                ('planned_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='data planejada')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('actual_active_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='tempo ativo real em minutos')),
                ('actual_additional_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Se ficar vazio, será usada a proporção dos custos previstos na ficha técnica.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='custos adicionais reais')),
                ('expiration_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='validade do lote produzido')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_batches_completed', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_batches_created', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches_received', to='inventory.stocklocation', verbose_name='local de destino do produto')),
                ('output_lot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_batch', to='inventory.stocklot', verbose_name='lote de estoque produzido')),
                ('output_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_output_batch', to='inventory.stockmovement', verbose_name='movimentação de entrada do produto')),
                ('recipe_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='recipes.recipeversion', verbose_name='versão da ficha técnica')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_batches_responsible', to=settings.AUTH_USER_MODEL, verbose_name='responsável pela produção')),
            ],
            options={
                'verbose_name': 'lote de produção',
                'verbose_name_plural': 'lotes de produção',
                'ordering': ['-planned_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='quantidade planejada')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='quantidade efetivamente utilizada')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observações')),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material', to='inventory.stockmovement', verbose_name='movimentação de consumo')),
                ('production_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.productionbatch', verbose_name='lote de produção')),
                ('recipe_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_materials', to='recipes.recipeingredient', verbose_name='ingrediente da ficha técnica')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_materials', to='inventory.stocklocation', verbose_name='local de origem')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_materials', to='inventory.stocklot', verbose_name='lote de estoque utilizado')),
            ],
            options={
                'verbose_name': 'material da produção',
                'verbose_name_plural': 'materiais da produção',
                'ordering': ['recipe_ingredient__sequence', 'stock_lot__expiration_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('skipped', 'Ignorada')], db_index=True, default='pending', max_length=20, verbose_name='situação')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciada em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_steps_performed', to=settings.AUTH_USER_MODEL, verbose_name='realizada por')),
                ('production_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='production.productionbatch', verbose_name='lote de produção')),
                ('recipe_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_executions', to='recipes.recipestep', verbose_name='etapa da ficha técnica')),
            ],
            options={
                'verbose_name': 'execução de etapa da produção',
                'verbose_name_plural': 'execuções das etapas da produção',
                'ordering': ['recipe_step__sequence', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('planned_quantity__gt', 0)), name='production_planned_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('actual_quantity__isnull', True), ('actual_quantity__gt', 0), _connector='OR'), name='production_actual_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('actual_additional_cost__isnull', True), ('actual_additional_cost__gte', 0), _connector='OR'), name='production_additional_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='production_completion_after_start'),
        ),
        migrations.AddConstraint(
            model_name='productionmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('planned_quantity__gt', 0)), name='production_material_planned_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('actual_quantity__isnull', True), ('actual_quantity__gte', 0), _connector='OR'), name='production_material_actual_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionmaterial',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_location__isnull', True), ('stock_lot__isnull', True)), models.Q(('source_location__isnull', False), ('stock_lot__isnull', False)), _connector='OR'), name='production_material_stock_fields_together'),
        ),
        migrations.AddConstraint(
            model_name='productionstepexecution',
            constraint=models.UniqueConstraint(fields=('production_batch', 'recipe_step'), name='production_step_batch_unique'),
        ),
        migrations.AddConstraint(
            model_name='productionstepexecution',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='production_step_completion_after_start'),
        ),
    ]
