# Generated by Django 5.2.17 on 2026-08-24 20:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import purchases.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='nome')),
                ('supplier_type', models.CharField(choices=[('company', 'Empresa'), ('individual', 'Pessoa física'), ('informal', 'Informal')], default='company', max_length=20, verbose_name='tipo')),
                ('tax_id', models.CharField(blank=True, db_index=True, max_length=18, verbose_name='CPF/CNPJ')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='pessoa de contato')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('address', models.TextField(blank=True, verbose_name='endereço')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='data da compra')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='data de recebimento')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ordered', 'Solicitada'), ('partially_received', 'Parcialmente recebida'), ('received', 'Recebida'), ('cancelled', 'Cancelada')], db_index=True, default='draft', max_length=20, verbose_name='situação')),
                ('channel', models.CharField(choices=[('physical_store', 'Loja física'), ('online', 'Online'), ('fair', 'Feira ou compra informal'), ('direct', 'Contato direto'), ('other', 'Outro')], default='physical_store', max_length=20, verbose_name='canal')),
                ('document_type', models.CharField(choices=[('invoice', 'Nota fiscal'), ('fiscal_receipt', 'Cupom fiscal'), ('receipt', 'Recibo'), ('no_document', 'Sem documento'), ('other', 'Outro')], default='no_document', max_length=20, verbose_name='tipo de comprovante')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='número do documento')),
                ('freight_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='frete')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='desconto geral')),
                ('other_costs_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='outros custos')),
                ('declared_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='total informado no comprovante')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_records_created', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_made', to=settings.AUTH_USER_MODEL, verbose_name='comprado por')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='purchases.supplier', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('invoice', 'Nota fiscal'), ('fiscal_receipt', 'Cupom fiscal'), ('receipt', 'Recibo'), ('payment_proof', 'Comprovante de pagamento'), ('other', 'Outro')], default='other', max_length=20, verbose_name='tipo de documento')),
                ('file', models.FileField(upload_to=purchases.models.purchase_document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='arquivo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='purchases.purchase', verbose_name='compra')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'documento da compra',
                'verbose_name_plural': 'documentos da compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial_quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='quantidade comercial')),
                ('base_quantity', models.DecimalField(decimal_places=6, help_text='Quantidade efetivamente recebida, expressa na unidade-base cadastrada para o item.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='quantidade efetiva na unidade-base')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='preço por unidade comercial')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='desconto do item')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('commercial_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.unitofmeasure', verbose_name='unidade comercial')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.item', verbose_name='item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase', verbose_name='compra')),
            ],
            options={
                'verbose_name': 'item da compra',
                'verbose_name_plural': 'itens da compra',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('commercial_quantity__gt', 0)), name='purchase_item_commercial_qty_positive'), models.CheckConstraint(condition=models.Q(('base_quantity__gt', 0)), name='purchase_item_base_qty_positive'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='purchase_item_unit_price_nonnegative'), models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='purchase_item_discount_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('method', models.CharField(choices=[('pix', 'Pix'), ('cash', 'Dinheiro'), ('debit_card', 'Cartão de débito'), ('credit_card', 'Cartão de crédito'), ('crypto', 'Cripto'), ('bank_transfer', 'Transferência bancária'), ('boleto', 'Boleto'), ('other', 'Outro')], max_length=20, verbose_name='forma de pagamento')),
                ('funding_source', models.CharField(choices=[('business_funds', 'Recursos do Pastifício'), ('owner_contribution', 'Aporte pessoal'), ('owner_reimbursable', 'Adiantamento pessoal reembolsável'), ('other', 'Outra origem')], default='business_funds', max_length=20, verbose_name='origem do dinheiro')),
                ('due_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='data de vencimento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='data do pagamento')),
                ('installment_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='número da parcela')),
                ('installment_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='total de parcelas')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado')], db_index=True, default='pending', max_length=20, verbose_name='situação')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchases.purchase', verbose_name='compra')),
            ],
            options={
                'verbose_name': 'pagamento da compra',
                'verbose_name_plural': 'pagamentos da compra',
                'ordering': ['due_date', 'installment_number', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='purchase_payment_amount_positive'), models.CheckConstraint(condition=models.Q(('installment_number__gt', 0)), name='purchase_payment_installment_number_positive'), models.CheckConstraint(condition=models.Q(('installment_count__gt', 0)), name='purchase_payment_installment_count_positive'), models.CheckConstraint(condition=models.Q(('installment_number__lte', models.F('installment_count'))), name='purchase_payment_installment_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('freight_amount__gte', 0)), name='purchase_freight_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='purchase_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('other_costs_amount__gte', 0)), name='purchase_other_costs_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('declared_total__isnull', True), ('declared_total__gte', 0), _connector='OR'), name='purchase_declared_total_nonnegative'),
        ),
    ]
