# Generated by Django 5.2.17 on 2026-08-27 21:13

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='non_business_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Parcela pessoal ou alheia ao negócio incluída no mesmo comprovante.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor não pertencente ao Pastifício'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('non_business_amount__gte', 0)), name='purchase_non_business_nonnegative'),
        ),
    ]
