# Generated by Django 5.2.17 on 2026-08-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchase_non_business_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'NF-e ou nota fiscal'), ('nfce', 'NFC-e (modelo 65)'), ('fiscal_receipt', 'Cupom fiscal (ECF)'), ('receipt', 'Recibo'), ('no_document', 'Sem documento'), ('other', 'Outro')], default='no_document', max_length=20, verbose_name='tipo de comprovante'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'NF-e ou nota fiscal'), ('nfce', 'NFC-e (modelo 65)'), ('fiscal_receipt', 'Cupom fiscal (ECF)'), ('receipt', 'Recibo'), ('payment_proof', 'Comprovante de pagamento'), ('other', 'Outro')], default='other', max_length=20, verbose_name='tipo de documento'),
        ),
    ]
