# Generated by Django 5.2.17 on 2026-09-22 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('purchases', '0003_alter_purchase_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='financial_account',
            field=models.ForeignKey(blank=True, help_text='Conta utilizada quando o pagamento é feito com recursos do Pastifício.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payments', to='finance.financialaccount', verbose_name='conta de pagamento'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='funded_by',
            field=models.ForeignKey(blank=True, help_text='Pessoa que forneceu o dinheiro em um aporte ou adiantamento pessoal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payments_funded', to=settings.AUTH_USER_MODEL, verbose_name='recursos pessoais de'),
        ),
    ]
