# Generated by Django 5.2.17 on 2026-09-01 17:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_brand_item_brand'),
        ('purchases', '0003_alter_purchase_document_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Identificador curto, como FREEZER-01.', max_length=30, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('location_type', models.CharField(choices=[('general', 'Armazenamento geral'), ('refrigerated', 'Refrigerado'), ('frozen', 'Congelado'), ('production', 'Área de produção'), ('in_transit', 'Em trânsito'), ('other', 'Outro')], default='general', max_length=20, verbose_name='tipo de local')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'local de estoque',
                'verbose_name_plural': 'locais de estoque',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='data e hora da contagem')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20, verbose_name='situação')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts_completed', to=settings.AUTH_USER_MODEL, verbose_name='concluído por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.stocklocation', verbose_name='local de estoque')),
            ],
            options={
                'verbose_name': 'contagem de estoque',
                'verbose_name_plural': 'contagens de estoque',
                'ordering': ['-counted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Identificador como LOT-2026-000001.', max_length=50, unique=True, verbose_name='código interno do lote')),
                ('supplier_lot_code', models.CharField(blank=True, max_length=100, verbose_name='lote informado pelo fornecedor')),
                ('received_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='data de recebimento')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='data de fabricação')),
                ('expiration_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='data de validade')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))], verbose_name='custo por unidade-base')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='bloqueado para utilização')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='catalog.item', verbose_name='item')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='purchases.purchaseitem', verbose_name='item de compra de origem')),
            ],
            options={
                'verbose_name': 'lote de estoque',
                'verbose_name_plural': 'lotes de estoque',
                'ordering': ['expiration_date', 'received_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='quantidade esperada')),
                ('counted_quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='quantidade contada')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observações')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount', verbose_name='contagem de estoque')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_lines', to='inventory.stocklot', verbose_name='lote')),
            ],
            options={
                'verbose_name': 'item da contagem',
                'verbose_name_plural': 'itens da contagem',
                'ordering': ['lot__item__name', 'lot__expiration_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('opening_balance', 'Saldo inicial'), ('purchase_receipt', 'Entrada por compra'), ('production_consumption', 'Consumo na produção'), ('production_output', 'Entrada da produção'), ('sale_dispatch', 'Saída por venda'), ('customer_return', 'Devolução de cliente'), ('supplier_return', 'Devolução ao fornecedor'), ('loss', 'Perda ou descarte'), ('adjustment_in', 'Ajuste de entrada'), ('adjustment_out', 'Ajuste de saída'), ('transfer', 'Transferência')], db_index=True, max_length=30, verbose_name='tipo de movimentação')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='quantidade na unidade-base')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='data e hora da movimentação')),
                ('reference', models.CharField(blank=True, help_text='Número da compra, produção, venda ou outro documento relacionado.', max_length=100, verbose_name='referência')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='inventory.stocklocation', verbose_name='local de destino')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocklot', verbose_name='lote')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='inventory.stocklocation', verbose_name='local de origem')),
            ],
            options={
                'verbose_name': 'movimentação de estoque',
                'verbose_name_plural': 'movimentações de estoque',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='stock_lot_unit_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.UniqueConstraint(fields=('stock_count', 'lot'), name='stock_count_lot_unique'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(('expected_quantity__gte', 0)), name='stock_count_expected_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(('counted_quantity__gte', 0)), name='stock_count_counted_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['lot', 'occurred_at'], name='stock_move_lot_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'occurred_at'], name='stock_move_type_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('source_location__isnull', False), ('destination_location__isnull', False), _connector='OR'), name='stock_movement_has_location'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('source_location__isnull', True), ('destination_location__isnull', True), models.Q(('source_location', models.F('destination_location')), _negated=True), _connector='OR'), name='stock_movement_locations_different'),
        ),
    ]
