# Generated by Django 5.2.17 on 2026-09-02 18:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockcountline',
            name='stock_count_counted_nonnegative',
        ),
        migrations.AlterField(
            model_name='stockcountline',
            name='counted_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))], verbose_name='quantidade contada'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(('counted_quantity__isnull', True), ('counted_quantity__gte', 0), _connector='OR'), name='stock_count_counted_nonnegative'),
        ),
    ]
