# Generated by Django 5.2.17 on 2026-08-24 15:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'categoria de item',
                'verbose_name_plural': 'categorias de itens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('symbol', models.CharField(max_length=20, verbose_name='símbolo')),
                ('dimension', models.CharField(choices=[('mass', 'Massa'), ('volume', 'Volume'), ('count', 'Contagem'), ('time', 'Tempo'), ('energy', 'Energia'), ('length', 'Comprimento'), ('other', 'Outro')], max_length=20, verbose_name='dimensão')),
                ('factor_to_base_unit', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='fator para a unidade-base')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'unidade de medida',
                'verbose_name_plural': 'unidades de medida',
                'ordering': ['dimension', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('item_type', models.CharField(choices=[('ingredient', 'Ingrediente ou insumo'), ('packaging', 'Embalagem'), ('consumable', 'Consumível'), ('intermediate', 'Produto intermediário'), ('finished_product', 'Produto acabado'), ('resale_product', 'Produto para revenda'), ('equipment', 'Equipamento'), ('service', 'Serviço'), ('other', 'Outro')], db_index=True, max_length=30, verbose_name='tipo de item')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('net_content_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='quantidade líquida')),
                ('is_purchasable', models.BooleanField(default=False, verbose_name='pode ser comprado')),
                ('is_producible', models.BooleanField(default=False, verbose_name='pode ser produzido')),
                ('is_sellable', models.BooleanField(default=False, verbose_name='pode ser vendido')),
                ('tracks_inventory', models.BooleanField(default=True, verbose_name='controla estoque')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='validade em dias')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.itemcategory', verbose_name='categoria')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_unit_items', to='catalog.unitofmeasure', verbose_name='unidade-base')),
                ('net_content_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='net_content_items', to='catalog.unitofmeasure', verbose_name='unidade do conteúdo líquido')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'itens',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('net_content_quantity__isnull', True), ('net_content_unit__isnull', True)), models.Q(('net_content_quantity__isnull', False), ('net_content_unit__isnull', False)), _connector='OR'), name='item_net_content_fields_together')],
            },
        ),
    ]
