# Generated by Django 5.2.17 on 2026-08-27 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gtin',
            field=models.CharField(blank=True, help_text='Número impresso abaixo do código de barras da embalagem.', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Informe um GTIN com 8, 12, 13 ou 14 dígitos.', regex='^(?:\\d{8}|\\d{12,14})$')], verbose_name='GTIN / código de barras'),
        ),
    ]
