# Generated by Django 5.2.17 on 2026-09-03 17:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_brand_item_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Identificador como REC-MASSA-001.', max_length=30, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes_created', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('output_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='catalog.item', verbose_name='item produzido')),
            ],
            options={
                'verbose_name': 'ficha técnica',
                'verbose_name_plural': 'fichas técnicas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='versão')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('archived', 'Arquivada')], db_index=True, default='draft', max_length=20, verbose_name='situação')),
                ('yield_quantity', models.DecimalField(decimal_places=6, help_text='Quantidade total obtida na unidade-base do item produzido.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='rendimento na unidade-base do produto')),
                ('active_time_minutes', models.PositiveIntegerField(default=0, help_text='Tempo efetivamente trabalhado, usado no cálculo da mão de obra.', verbose_name='tempo de trabalho ativo em minutos')),
                ('total_time_minutes', models.PositiveIntegerField(blank=True, help_text='Inclui descansos, resfriamento, congelamento e outras esperas.', null=True, verbose_name='tempo total do processo em minutos')),
                ('hourly_labor_cost', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='custo da hora de trabalho')),
                ('valid_from', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='válida a partir de')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válida até')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovada em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_versions_approved', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='recipes.recipe', verbose_name='ficha técnica')),
            ],
            options={
                'verbose_name': 'versão da ficha técnica',
                'verbose_name_plural': 'versões das fichas técnicas',
                'ordering': ['recipe', '-version'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ordem')),
                ('phase', models.CharField(blank=True, help_text='Exemplo: dia 1, dia 2, massa ou recheio.', max_length=100, verbose_name='fase')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('instructions', models.TextField(verbose_name='instruções')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='duração estimada em minutos')),
                ('requires_active_work', models.BooleanField(default=True, help_text='Desmarque para descanso, resfriamento ou congelamento sem trabalho contínuo.', verbose_name='exige trabalho ativo')),
                ('recipe_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipeversion', verbose_name='versão da ficha técnica')),
            ],
            options={
                'verbose_name': 'etapa da ficha técnica',
                'verbose_name_plural': 'etapas da ficha técnica',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ordem')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='quantidade na unidade-base')),
                ('unit_cost_override', models.DecimalField(blank=True, decimal_places=8, help_text='Deixe vazio para utilizar o custo do lote mais recente no estoque.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))], verbose_name='custo informado por unidade-base')),
                ('stage', models.CharField(blank=True, help_text='Exemplo: massa, recheio ou finalização.', max_length=100, verbose_name='etapa de utilização')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observações')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_uses', to='catalog.item', verbose_name='ingrediente ou insumo')),
                ('recipe_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipeversion', verbose_name='versão da ficha técnica')),
            ],
            options={
                'verbose_name': 'ingrediente da ficha técnica',
                'verbose_name_plural': 'ingredientes da ficha técnica',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeAdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_type', models.CharField(choices=[('energy', 'Energia elétrica'), ('gas', 'Gás'), ('water', 'Água'), ('equipment', 'Uso ou depreciação de equipamento'), ('consumable', 'Material de consumo'), ('other', 'Outro')], max_length=20, verbose_name='tipo de custo')),
                ('description', models.CharField(max_length=150, verbose_name='descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observações')),
                ('recipe_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_costs', to='recipes.recipeversion', verbose_name='versão da ficha técnica')),
            ],
            options={
                'verbose_name': 'custo adicional da ficha técnica',
                'verbose_name_plural': 'custos adicionais da ficha técnica',
                'ordering': ['cost_type', 'description', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.UniqueConstraint(fields=('recipe', 'version'), name='recipe_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('recipe',), name='recipe_one_active_version'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='recipe_version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(('yield_quantity__gt', 0)), name='recipe_version_yield_positive'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_labor_cost__gte', 0)), name='recipe_version_labor_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(('total_time_minutes__isnull', True), ('total_time_minutes__gte', models.F('active_time_minutes')), _connector='OR'), name='recipe_total_time_valid'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='recipe_version_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='recipestep',
            constraint=models.UniqueConstraint(fields=('recipe_version', 'sequence'), name='recipe_step_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='recipestep',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='recipe_step_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe_version', 'sequence'), name='recipe_ingredient_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='recipe_ingredient_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='recipe_ingredient_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_override__isnull', True), ('unit_cost_override__gte', 0), _connector='OR'), name='recipe_ingredient_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='recipeadditionalcost',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='recipe_additional_cost_nonnegative'),
        ),
    ]
