# Generated by Django 5.2.17 on 2026-09-04 21:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_brand_item_brand'),
        ('inventory', '0002_remove_stockcountline_stock_count_counted_nonnegative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('customer_type', models.CharField(choices=[('individual', 'Pessoa física'), ('company', 'Pessoa jurídica')], default='individual', max_length=20, verbose_name='tipo de cliente')),
                ('tax_id', models.CharField(blank=True, help_text='Informe somente os números.', max_length=14, null=True, unique=True, verbose_name='CPF / CNPJ')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='pessoa de contato')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('address', models.TextField(blank=True, verbose_name='endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('postal_code', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Identificador como PED-2026-000001.', max_length=50, unique=True, verbose_name='número do pedido')),
                ('ordered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='data e hora do pedido')),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='data e hora combinadas')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluído em')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado'), ('in_production', 'Em produção'), ('ready', 'Pronto'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20, verbose_name='situação')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('website', 'Site'), ('direct', 'Contato direto'), ('physical', 'Venda presencial'), ('partner', 'Parceiro ou ponto de venda'), ('other', 'Outro')], default='whatsapp', max_length=20, verbose_name='canal da venda')),
                ('fulfillment_type', models.CharField(choices=[('pickup', 'Retirada'), ('own_delivery', 'Entrega própria'), ('courier', 'Motoboy ou transportadora'), ('partner_location', 'Retirada em parceiro'), ('other', 'Outro')], default='pickup', max_length=20, verbose_name='forma de entrega ou retirada')),
                ('delivery_address', models.TextField(blank=True, help_text='Registre aqui o endereço utilizado neste pedido. Assim o histórico não muda se o cliente se mudar.', verbose_name='endereço da entrega')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='desconto geral')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de entrega cobrado do cliente.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='taxa de entrega cobrada')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo suportado pelo Pastifício, como combustível ou motoboy.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='custo real da entrega')),
                ('other_charges_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='outros valores cobrados')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
                ('customer', models.ForeignKey(blank=True, help_text='Pode ficar vazio para uma venda não identificada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='sales.customer', verbose_name='cliente')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_sold', to=settings.AUTH_USER_MODEL, verbose_name='responsável pela venda')),
            ],
            options={
                'verbose_name': 'pedido de venda',
                'verbose_name_plural': 'pedidos de venda',
                'ordering': ['-ordered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial_quantity', models.DecimalField(decimal_places=4, help_text='Exemplo: 2 pacotes.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='quantidade comercial')),
                ('base_quantity', models.DecimalField(decimal_places=6, help_text='Quantidade total que sairá do estoque. Exemplo: 2 pacotes de 300 g = 600 g.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='quantidade total na unidade-base')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='preço por unidade comercial')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='desconto do item')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('commercial_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_items', to='catalog.unitofmeasure', verbose_name='unidade comercial')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_items', to='catalog.item', verbose_name='item vendido')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder', verbose_name='pedido de venda')),
            ],
            options={
                'verbose_name': 'item do pedido de venda',
                'verbose_name_plural': 'itens do pedido de venda',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='quantidade na unidade-base')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=8, help_text='Será copiado do lote quando a saída do estoque for registrada.', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))], verbose_name='custo por unidade-base no momento da venda')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observações')),
                ('dispatch_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_dispatch_allocation', to='inventory.stockmovement', verbose_name='movimentação de saída')),
                ('return_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_allocation', to='inventory.stockmovement', verbose_name='movimentação de devolução')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_allocations', to='sales.salesorderitem', verbose_name='item do pedido')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_allocations', to='inventory.stocklocation', verbose_name='local de origem')),
                ('stock_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_allocations', to='inventory.stocklot', verbose_name='lote de estoque')),
            ],
            options={
                'verbose_name': 'separação de estoque da venda',
                'verbose_name_plural': 'separações de estoque da venda',
                'ordering': ['sales_order_item', 'stock_lot__expiration_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor cobrado')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Exemplo: taxa do cartão ou do Mercado Pago.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='taxa do meio de pagamento')),
                ('method', models.CharField(choices=[('pix', 'Pix'), ('cash', 'Dinheiro'), ('debit_card', 'Cartão de débito'), ('credit_card', 'Cartão de crédito'), ('crypto', 'Cripto'), ('bank_transfer', 'Transferência bancária'), ('other', 'Outro')], max_length=20, verbose_name='forma de pagamento')),
                ('due_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='data de vencimento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('installment_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='número da parcela')),
                ('installment_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='total de parcelas')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado')], db_index=True, default='pending', max_length=20, verbose_name='situação')),
                ('processor_reference', models.CharField(blank=True, help_text='Identificador do Pix, cartão ou intermediador, quando disponível.', max_length=100, verbose_name='referência da transação')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_payments_received', to=settings.AUTH_USER_MODEL, verbose_name='recebido por')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesorder', verbose_name='pedido de venda')),
            ],
            options={
                'verbose_name': 'pagamento do pedido',
                'verbose_name_plural': 'pagamentos do pedido',
                'ordering': ['due_date', 'installment_number', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='sales_order_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0)), name='sales_order_delivery_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_cost__gte', 0)), name='sales_order_delivery_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('other_charges_amount__gte', 0)), name='sales_order_other_charges_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_for__isnull', True), ('scheduled_for__gte', models.F('ordered_at')), _connector='OR'), name='sales_order_schedule_after_order'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('ordered_at')), _connector='OR'), name='sales_order_completion_after_order'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('commercial_quantity__gt', 0)), name='sales_item_commercial_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('base_quantity__gt', 0)), name='sales_item_base_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sales_item_unit_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='sales_item_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitemallocation',
            constraint=models.UniqueConstraint(fields=('sales_order_item', 'stock_lot', 'source_location'), name='sales_allocation_item_lot_location_unique'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitemallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_allocation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitemallocation',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='sales_allocation_unit_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesorderpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sales_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderpayment',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount__gte', 0)), name='sales_payment_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesorderpayment',
            constraint=models.CheckConstraint(condition=models.Q(('installment_number__gt', 0)), name='sales_payment_installment_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderpayment',
            constraint=models.CheckConstraint(condition=models.Q(('installment_count__gt', 0)), name='sales_payment_installment_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderpayment',
            constraint=models.CheckConstraint(condition=models.Q(('installment_number__lte', models.F('installment_count'))), name='sales_payment_installment_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesorderpayment',
            constraint=models.CheckConstraint(condition=models.Q(('fee_amount__lte', models.F('amount'))), name='sales_payment_fee_not_greater_than_amount'),
        ),
    ]
