# Generated by Django 5.2.17 on 2026-09-12 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_stockcountline_stock_count_counted_nonnegative_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='source_location',
            field=models.ForeignKey(blank=True, help_text='Local padrão de onde sairão os produtos deste pedido.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_fulfilled', to='inventory.stocklocation', verbose_name='local de separação do estoque'),
        ),
    ]
