# Generated by Django 5.2.17 on 2026-09-22 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('sales', '0002_salesorder_source_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderpayment',
            name='financial_account',
            field=models.ForeignKey(blank=True, help_text='Conta em que o recebimento do Pastifício será registrado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_payments', to='finance.financialaccount', verbose_name='conta de recebimento'),
        ),
    ]
